[tool.poetry]
name = "a-maze-ing"
version = "1.0.0"
description = "A-Maze-ing maze generator and renderer"
authors = ["jcascale y mjabalqu"]
# Le indicamos a Poetry dónde está tu código
packages = [
    { include = "mazegen*" },
    { include = "a_maze_ing.py" },
    { include = "render.py" },
    { include = "get_maze_data.py" }
]

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry.scripts]
play_maze = "a_maze_ing:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"